language: python

os:
- linux

python:
- 2.7
- 3.4
- 3.5
- 3.6
- nightly

before_install:
- openssl aes-256-cbc -K $encrypted_e7f042a9cf96_key -iv $encrypted_e7f042a9cf96_iv
  -in settings.yml.enc -out settings.yml -d

install:
# Sometimes, only lxml master branch compiles with Python nightly
# - if [[ "$( python --version | grep 'a' )" ]] ; then pip install cython && pip install git+https://github.com/lxml/lxml.git ; fi
- pip install .
# Install test dependencies manually since we're calling tests/__init__.py directly in the 'script' section
- pip install PyYAML requests_mock psutil
- pip install coverage
- pip install coveralls

script:
- coverage run --source=exchangelib setup.py test

after_success: coveralls

jobs:
  include:
    - stage: wipe_test_account
      # Wipe contents of the test account after a complete build, to avoid account going over quota
      script: python tests/__init__.py -q EWSTest.wipe_test_account
      python: 3.6
      os: linux
